# 
# inspiration taken from http://www.virtualroadside.com/blog/index.php/2017/01/14/integrated-subproject-sites-on-readthedocs-org/
# new version at: https://github.com/robotpy/robotpy-sphinx-plugin
# Author: Tzaphkiel
# 
class SidebarGenerator:
  def __init__(self, conf, project):
    self.conf = conf
    self.project = project
    self.version = self.conf['rtdVersion']
    self.intersphinx_mapping = self.conf['intersphinx_mapping']
    self.lines = ["", ".. DO NOT MODIFY! AUTOGENERATED CONTENT!", ""]



  def toctree(self, caption, depth=2):
    self.lines.extend(
        [".. toctree::",
         "    :caption: %s" % caption,
         "    :maxdepth: %s" % depth,
         "    :hidden:",
         "    :glob:",
         ""]
    )
    return self



  def newLine(self):
    self.lines.append("")
    return self



  def sdmxLocalToc(self, desc, link, mapId=""):
    if not mapId:
      args = desc, link
    else:
      args = (
          desc,
          "%s/%s" % (self.intersphinx_mapping[mapId][0], link),
      )
    
    if not desc:
      self.lines.append("    %s" % args[1])
    else:
      self.lines.append("    %s <%s>" % args)
    return self



  def subPrjToc(self, project, desc):
    if project != self.project:
      args = desc, project, self.version
      self.lines.append(
        "    %s <http://docs.sdmx.org/projects/%s/en/%s/toc.html>"
        % args
      )
    else:
      self.lines.append("    %s <toc>" % desc)
    return self



  def writeIfChanged(self, fname):
    contents = "\n".join(self.lines)
    try:
      with open(fname, "r") as fp:
        old_contents = fp.read()
    except:
      old_contents = ""

    if old_contents != contents:
      with open(fname, "w") as fp:
        fp.write(contents)


